package smtp

type SmtpSessionState int

const (
	SMTP_SERVER_BUILD_STRING = "Milhaux SMTP Server"
)

const (
	SMTP_SERVER_STATE_INVALID = SmtpSessionState(iota)
	SMTP_SERVER_STATE_ESTABLISH
	SMTP_SERVER_STATE_GOTHELO
	SMTP_SERVER_STATE_MAIL
	SMTP_SERVER_STATE_RCPT
	SMTP_SERVER_STATE_DATA
	SMTP_SERVER_STATE_DONE
	SMTP_SERVER_STATE_EXIT
)

const (
	SMTP_COMMAND_STATUS_NONE                    = 0
	SMTP_COMMAND_STATUS_SERVICE_READY           = 220
	SMTP_COMMAND_STATUS_MAIL_ACTION_OK          = 250
	SMTP_COMMAND_STATUS_SERVICE_CLOSING_CHANNEL = 221
	SMTP_COMMAND_STATUS_START_MAIL_INPUT        = 354
	SMTP_COMMAND_STATUS_COMMAND_NOT_IMPLEMENTED = 502
	SMTP_COMMAND_STATUS_BAD_COMMAND_SEQUENCE    = 503

	SMTP_COMMAND_MAIL = "MAIL"
	SMTP_COMMAND_RCPT = "RCPT"
	SMTP_COMMAND_DATA = "DATA"
	SMTP_COMMAND_DONE = "QUIT"
)
